import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'astro/config';
import { addNoteImageGeometryToHtml, readNoteImageMetadata } from './tools/note-image-metadata.mjs';

const rootDir = path.dirname(fileURLToPath(import.meta.url));
const generatedNotesMarker =
  '<!-- Generated by scripts/sync-obsidian-notes.mjs from Obsidian Publish. Do not edit by hand. -->';
const contentImageFlag = 'astroContentImageFlag';
const contentAssetsFile = '.astro/content-assets.mjs';
const astroContentRuntimeFile = 'node_modules/astro/dist/content/runtime.js';
const virtualNoteAssetId = 'virtual:generated-note-asset';
const virtualNoteAssetPrefix = '\0generated-note-asset:';
const imageExtensions = new Set(['.avif', '.bmp', '.gif', '.jpeg', '.jpg', '.png', '.svg', '.webp']);
const generatedNoteCache = new Map();

export function generatedNoteAssetFallback() {
  return {
    name: 'generated-note-asset-fallback',
    enforce: 'pre',
    transform(source, id) {
      const filePath = slash(path.relative(rootDir, path.normalize(id.split('?')[0])));

      if (filePath === astroContentRuntimeFile) {
        return transformAstroContentRuntime(source);
      }

      if (filePath !== contentAssetsFile) {
        return null;
      }

      return transformContentAssetImports(source);
    },
    resolveId(id) {
      if (!id.startsWith(`${virtualNoteAssetId}?`)) {
        return null;
      }

      return `${virtualNoteAssetPrefix}${id.slice(virtualNoteAssetId.length + 1)}`;
    },
    load(id) {
      if (!id.startsWith(virtualNoteAssetPrefix)) {
        return null;
      }

      const params = new URLSearchParams(id.slice(virtualNoteAssetPrefix.length));
      const publicPath = decodeAssetPath(params.get('data') ?? '');
      const { width, height } = readNoteImageMetadata(publicPath);
      const sentinel = { __generatedNoteAssetFallback: true, src: publicPath, width, height };
      return `export default ${JSON.stringify(sentinel)};`;
    },
  };
}

export function generatedNoteImageGeometry() {
  return {
    name: 'generated-note-image-geometry',
    hooks: {
      'astro:build:done': ({ dir }) => {
        const notesDirectory = fileURLToPath(new URL('notes/', dir));
        annotateBuiltNoteHtml(notesDirectory);
      },
    },
  };
}

function annotateBuiltNoteHtml(directory) {
  if (!existsSync(directory)) return;
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const target = path.join(directory, entry.name);
    if (entry.isDirectory()) annotateBuiltNoteHtml(target);
    else if (entry.name === 'index.html') {
      const source = readFileSync(target, 'utf8');
      const annotated = addNoteImageGeometryToHtml(source);
      if (annotated !== source) writeFileSync(target, annotated);
    }
  }
}

function transformContentAssetImports(source) {
  let changed = false;
  const code = source.replace(
    /from\s+(["'])([^"']+\?[^"']*astroContentImageFlag[^"']*)\1/g,
    (match, quote, specifier) => {
      const publicPath = publicPathForMissingGeneratedNoteAsset(specifier);

      if (!publicPath) {
        return match;
      }

      changed = true;
      return `from ${quote}${virtualNoteAssetId}?data=${encodeAssetPath(publicPath)}${quote}`;
    },
  );

  return changed ? { code, map: null } : null;
}

function transformAstroContentRuntime(source) {
  const target = 'image = await getImage({ ...decodedImagePath, src: imported });';

  if (!source.includes(target)) {
    throw new Error(
      `generated-note-asset-fallback could not patch ${astroContentRuntimeFile}; ` +
      'the Astro content image runtime contract changed',
    );
  }

  const replacement = `if (imported?.__generatedNoteAssetFallback === true) {
          image = {
            src: imported.src,
            srcSet: { attribute: null },
            attributes: {
              alt: decodedImagePath.alt,
              width: imported.width,
              height: imported.height,
              loading: "lazy",
              decoding: "async"
            }
          };
        } else {
          image = await getImage({ ...decodedImagePath, src: imported });
        }`;

  return {
    code: source.replace(target, replacement),
    map: null,
  };
}

function publicPathForMissingGeneratedNoteAsset(specifier) {
  if (!specifier.includes(contentImageFlag)) {
    return null;
  }

  const [rawTarget, rawQuery = ''] = specifier.split('?');
  const params = new URLSearchParams(rawQuery);
  const importer = params.get('importer');

  if (!importer) {
    return null;
  }

  const importerPath = path.resolve(rootDir, importer);
  const relativeImporter = slash(path.relative(rootDir, importerPath));
  if (!relativeImporter.startsWith('src/content/notes/') || !isGeneratedNote(importerPath)) {
    return null;
  }

  const cleanTarget = cleanMarkdownUrl(rawTarget);
  if (!isLocalImagePath(cleanTarget)) {
    return null;
  }

  const localTarget = path.resolve(path.dirname(importerPath), cleanTarget);
  if (existsSync(localTarget)) {
    return null;
  }

  const noteSlug = path.basename(importerPath, path.extname(importerPath));
  return `/notes-assets/${noteSlug}/${safeAssetName(path.basename(cleanTarget))}`;
}

function isGeneratedNote(filePath) {
  if (generatedNoteCache.has(filePath)) {
    return generatedNoteCache.get(filePath);
  }

  try {
    const isGenerated = readFileSync(filePath, 'utf8').includes(generatedNotesMarker);
    generatedNoteCache.set(filePath, isGenerated);
    return isGenerated;
  } catch {
    generatedNoteCache.set(filePath, false);
    return false;
  }
}

function cleanMarkdownUrl(value) {
  const unwrapped = value.trim().replace(/^<|>$/g, '').split('#')[0].split('?')[0];

  try {
    return decodeURIComponent(unwrapped);
  } catch {
    return unwrapped;
  }
}

function isLocalImagePath(value) {
  if (!value || value.startsWith('/') || /^(?:https?:|mailto:|tel:|data:)/i.test(value)) {
    return false;
  }

  return imageExtensions.has(path.extname(value).toLowerCase());
}

function safeAssetName(value) {
  const extension = path.extname(value);
  const stem = path.basename(value, extension);
  const safeStem = slugify(stem) || `asset-${shortHash(value)}`;
  return `${safeStem}${extension.toLowerCase()}`;
}

function encodeAssetPath(value) {
  return Buffer.from(value, 'utf8').toString('base64url');
}

function decodeAssetPath(value) {
  return Buffer.from(value, 'base64url').toString('utf8');
}

function slugify(value) {
  return String(value)
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim()
    .toLowerCase()
    .replace(/&/g, ' ')
    .replace(/[\\/]+/g, ' ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function shortHash(value) {
  let hash = 0;
  for (let index = 0; index < value.length; index += 1) {
    hash = (hash * 31 + value.charCodeAt(index)) >>> 0;
  }
  return hash.toString(36).slice(0, 6);
}

function slash(value) {
  return value.replace(/\\/g, '/');
}

export default defineConfig({
  site: 'https://horacech.github.io',
  output: 'static',
  publicDir: './astro-public',
  cacheDir: '.astro/cache',
  integrations: [generatedNoteImageGeometry()],
  vite: {
    cacheDir: '.astro/vite',
    plugins: [generatedNoteAssetFallback()],
  },
});
