import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import test from 'node:test';

const execFileAsync = promisify(execFile);
const script = path.resolve('tools/sync-obsidian-notes.mjs');

async function runSync(cwd, extraArgs = []) {
  return execFileAsync(
    process.execPath,
    [script, '--source', 'source', '--out', 'out', '--assets', 'assets', ...extraArgs],
    { cwd, encoding: 'utf8' },
  );
}

function bodyOf(markdown) {
  return markdown.split('---\n').slice(2).join('---\n').replace(/^.*Generated by[^\n]*\n\n/, '');
}

test('normalizes nested callouts and fences while degrading supported math outside code', async (t) => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'note-body-normalization-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(path.join(root, 'source'), { recursive: true });

  await writeFile(
    path.join(root, 'source', 'syntax.md'),
    [
      '# Reader heading with [a link](https://example.com)',
      '',
      '> [!ATTENTION]',
      '> Cost is $O(n)$ and $0 \\leq index \\textless length$.',
      '> >[!QUESTION] Nested question',
      '> > Nested answer.',
      '',
      '> [!EXAMPLE]',
      '> ```C',
      '> printf("$O(n)$ and \\leq stay code");',
      '> ```',
      '',
      '> [!TIP] >```C',
      '> int value = 1;',
      '> ```',
      '',
      '```Python',
      '$O(n)$ and \\lceil remain fenced',
      '```',
      '~~~SHELL',
      'printf "$HOME"',
      '~~~',
      '',
      'Display: $$x = \\frac{a}{b} \\times 2, \\quad y = \\lceil z \\rceil$$',
      'Inline code: `$O(n)$` and a [link](https://example.com/$value$).',
      '',
    ].join('\n'),
  );

  const firstRun = await runSync(root);
  assert.match(firstRun.stdout, /Warnings: none/);
  const body = bodyOf(await readFile(path.join(root, 'out', 'syntax.md'), 'utf8'));
  assert.match(body, /^## Reader heading with \[a link]\(https:\/\/example\.com\)$/m);
  assert.match(body, /^> \*\*ATTENTION\*\*$/m);
  assert.match(body, /^> Cost is O\(n\) and 0 ≤ index < length\.$/m);
  assert.match(body, /^> > \*\*QUESTION: Nested question\*\*$/m);
  assert.match(body, /^> ```c\n> printf\("\$O\(n\)\$ and \\leq stay code"\);\n> ```$/m);
  assert.match(body, /^> \*\*TIP\*\*\n> ```c\n> int value = 1;\n> ```$/m);
  assert.match(body, /```python\n\$O\(n\)\$ and \\lceil remain fenced\n```/);
  assert.match(body, /~~~shell\nprintf "\$HOME"\n~~~/);
  assert.match(body, /Display: x = \(a\)\/\(b\) × 2, y = ⌈ z ⌉/);
  assert.match(body, /Inline code: `\$O\(n\)\$` and a \[link]\(https:\/\/example\.com\/\$value\$\)\./);
  assert.doesNotMatch(body, /\[!(?:ATTENTION|QUESTION|EXAMPLE|TIP)\]|ATTENTION: >|TIP: >```/);

  const secondRun = await runSync(root);
  assert.match(secondRun.stdout, /unchanged out\/syntax\.md/);
});

test('warns and fails strict mode for unsupported TeX while keeping readable text', async (t) => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'note-unsupported-math-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(path.join(root, 'source'), { recursive: true });
  await writeFile(path.join(root, 'source', 'unknown.md'), 'Value: $\\mystery{x} + 1$.\n');

  const firstRun = await runSync(root);
  assert.match(firstRun.stdout, /\[math\].*unsupported TeX.*\\mystery/i);
  const body = bodyOf(await readFile(path.join(root, 'out', 'unknown.md'), 'utf8'));
  assert.match(body, /Value: mysteryx \+ 1\./);
  assert.doesNotMatch(body, /\$|\\mystery/);

  await assert.rejects(runSync(root, ['--strict']), (error) => {
    assert.equal(error.code, 1);
    assert.match(error.stdout, /Blocking errors: 1/);
    assert.match(error.stdout, /\[math\].*\\mystery/i);
    return true;
  });
});
