import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import test from 'node:test';

const execFileAsync = promisify(execFile);
const script = path.resolve('tools/sync-obsidian-notes.mjs');

async function runSync(cwd, extraArgs = []) {
  return execFileAsync(
    process.execPath,
    [script, '--source', 'source', '--out', 'out', '--assets', 'assets', ...extraArgs],
    { cwd, encoding: 'utf8' },
  );
}

function bodyOf(markdown) {
  return markdown.split('---\n').slice(2).join('---\n').replace(/^.*Generated by[^\n]*\n\n/, '');
}

test('rewrites Note fragments from renderer-compatible final heading IDs', async (t) => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'note-fragment-contract-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(path.join(root, 'source'), { recursive: true });

  await writeFile(
    path.join(root, 'source', 'target.md'),
    [
      '# ASCII码表',
      '# for循环 的用法',
      '# while循环 和 do while循环 的用法',
      '# 布尔型`_Bool`',
      '# Repeat',
      '# Repeat',
      '',
    ].join('\n'),
  );
  await writeFile(
    path.join(root, 'source', 'source.md'),
    [
      '# 二叉树遍历',
      '## 前序遍历',
      '## 中序遍历',
      '',
      'Cross: [[target#ASCII|ASCII]], [[target#for|for]], and [[target#while-do-while|loops]].',
      'Absolute: [ASCII table](/notes/target/#ascii).',
      'Rendered inline code: [boolean](/notes/target/#布尔型bool).',
      'Duplicates: [[target#Repeat|first]] and [second](/notes/target/#repeat-1).',
      'Placeholders: [前序遍历](#) and [中序遍历](#).',
      'External remains [example](https://example.com/#section).',
      'Inline code remains `[前序遍历](#)`.',
      '',
      '```md',
      '[前序遍历](#)',
      '```',
      '',
    ].join('\n'),
  );

  const firstRun = await runSync(root);
  assert.match(firstRun.stdout, /Warnings: none/);
  const source = bodyOf(await readFile(path.join(root, 'out', 'source.md'), 'utf8'));
  assert.match(source, /\[ASCII\]\(\/notes\/target\/#ascii码表\)/);
  assert.match(source, /\[for\]\(\/notes\/target\/#for循环-的用法\)/);
  assert.match(source, /\[loops\]\(\/notes\/target\/#while循环-和-do-while循环-的用法\)/);
  assert.match(source, /\[ASCII table\]\(\/notes\/target\/#ascii码表\)/);
  assert.match(source, /\[boolean\]\(\/notes\/target\/#布尔型_bool\)/);
  assert.match(source, /\[first\]\(\/notes\/target\/#repeat\)/);
  assert.match(source, /\[second\]\(\/notes\/target\/#repeat-1\)/);
  assert.match(source, /\[前序遍历\]\(#前序遍历\)/);
  assert.match(source, /\[中序遍历\]\(#中序遍历\)/);
  assert.match(source, /\[example\]\(https:\/\/example\.com\/#section\)/);
  assert.match(source, /`\[前序遍历\]\(#\)`/);
  assert.match(source, /```md\n\[前序遍历\]\(#\)\n```/);

  const secondRun = await runSync(root);
  assert.match(secondRun.stdout, /unchanged out\/source\.md/);
  assert.match(secondRun.stdout, /unchanged out\/target\.md/);
});

test('warns and fails strict mode for unresolved fragments in published Notes', async (t) => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'note-unresolved-fragment-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(path.join(root, 'source'), { recursive: true });
  await writeFile(path.join(root, 'source', 'target.md'), '# Existing section\n');
  await writeFile(path.join(root, 'source', 'source.md'), '[[target#Missing section|missing]]\n');

  const firstRun = await runSync(root);
  assert.match(firstRun.stdout, /\[fragment\].*Unresolved published Note fragment.*missing-section/i);
  const source = bodyOf(await readFile(path.join(root, 'out', 'source.md'), 'utf8'));
  assert.match(source, /\[missing\]\(\/notes\/target\/#missing-section\)/);

  await assert.rejects(runSync(root, ['--strict']), (error) => {
    assert.equal(error.code, 1);
    assert.match(error.stdout, /Blocking errors: 1/);
    assert.match(error.stdout, /\[fragment\]/);
    return true;
  });
});
