import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import test from 'node:test';

const execFileAsync = promisify(execFile);
const script = path.resolve('tools/sync-obsidian-notes.mjs');

async function runSync(cwd) {
  return execFileAsync(
    process.execPath,
    [script, '--source', 'source', '--out', 'out', '--assets', 'assets'],
    { cwd, encoding: 'utf8' },
  );
}

function bodyOf(markdown) {
  return markdown.split('---\n').slice(2).join('---\n').replace(/^.*Generated by[^\n]*\n\n/, '');
}

test('demotes semantic H1-based hierarchies without changing heading text or code', async (t) => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'note-heading-normalization-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(path.join(root, 'source'), { recursive: true });

  await writeFile(
    path.join(root, 'source', 'mixed.md'),
    [
      '# 1. Introduction',
      '## Detail',
      '# Duplicate title',
      '# Duplicate title',
      '',
      '```md',
      '# Fenced H1',
      '## Fenced H2',
      '```',
      '',
      '> [!NOTE] Callout',
      '> # Callout heading',
      '> ## Callout detail',
      '',
      '> ```md',
      '> # Blockquoted fence H1',
      '> ```',
      '',
      '> **EXAMPLE: > ```C**',
      '> int value = 1;',
      '> ```',
      '> > **ATTENTION**',
      '> > Nested callout text.',
      '',
      '# Heading after an implicitly closed blockquote fence',
      '',
    ].join('\n'),
  );
  await writeFile(path.join(root, 'source', 'h2-only.md'), '## Existing section\n\n### Existing detail\n');

  const result = await runSync(root);
  assert.doesNotMatch(result.stdout, /\[heading\]/);

  const mixed = bodyOf(await readFile(path.join(root, 'out', 'mixed.md'), 'utf8'));
  assert.match(mixed, /^## 1\. Introduction$/m);
  assert.match(mixed, /^### Detail$/m);
  assert.equal((mixed.match(/^## Duplicate title$/gm) || []).length, 2);
  assert.match(mixed, /```md\n# Fenced H1\n## Fenced H2\n```/);
  assert.match(mixed, /^> \*\*NOTE: Callout\*\*$/m);
  assert.match(mixed, /^> ## Callout heading$/m);
  assert.match(mixed, /^> ### Callout detail$/m);
  assert.match(mixed, /^> ```md\n> # Blockquoted fence H1\n> ```$/m);
  assert.match(mixed, /^## Heading after an implicitly closed blockquote fence$/m);

  const h2Only = bodyOf(await readFile(path.join(root, 'out', 'h2-only.md'), 'utf8'));
  assert.match(h2Only, /^## Existing section$/m);
  assert.match(h2Only, /^### Existing detail$/m);

  const secondRun = await runSync(root);
  assert.match(secondRun.stdout, /unchanged out\/mixed\.md/);
  assert.match(secondRun.stdout, /unchanged out\/h2-only\.md/);
});
