import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { mkdtemp, mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import test from 'node:test';

const execFileAsync = promisify(execFile);
const script = path.resolve('tools/sync-obsidian-notes.mjs');
const generatedMarker =
  '<!-- Generated by scripts/sync-obsidian-notes.mjs from Obsidian Publish. Do not edit by hand. -->';

async function runSync(cwd, args = []) {
  return execFileAsync(
    process.execPath,
    [script, '--source', 'source', '--out', 'out', '--assets', 'assets', ...args],
    { cwd, encoding: 'utf8' },
  );
}

test('default sync reconciles only stale generated notes and assets and is idempotent', async (t) => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'note-sync-reconcile-'));
  t.after(() => rm(root, { recursive: true, force: true }));

  await mkdir(path.join(root, 'source'), { recursive: true });
  await mkdir(path.join(root, 'out'), { recursive: true });
  await mkdir(path.join(root, 'assets', 'stale'), { recursive: true });
  await mkdir(path.join(root, 'assets', 'current'), { recursive: true });
  await writeFile(path.join(root, 'source', 'current.md'), '# Current\n\nApproved content.\n');
  await writeFile(path.join(root, 'source', '00 RAW LIST.md'), '# Publication control\n');
  await writeFile(path.join(root, 'source', 'AGENTS.override.md'), '# Agent instructions\n');
  await writeFile(path.join(root, 'out', 'stale.md'), `${generatedMarker}\n\n# Stale\n`);
  await writeFile(path.join(root, 'out', 'hand-written.md'), '# Hand-written\n');
  await writeFile(path.join(root, 'assets', 'stale', 'orphan.png'), 'stale asset');
  await writeFile(path.join(root, 'assets', 'current', 'obsolete.png'), 'obsolete asset');
  await writeFile(
    path.join(root, 'assets', '.obsidian-notes-sync-manifest.json'),
    `${JSON.stringify(
      {
        assets: ['assets/current/obsolete.png'],
        generatedAt: '2026-01-01T00:00:00.000Z',
        noteRecords: [],
        notes: [],
      },
      null,
      2,
    )}\n`,
  );

  const dryRun = await runSync(root, ['--dry-run']);
  assert.match(dryRun.stdout, /would remove out\/stale\.md/);
  assert.match(dryRun.stdout, /would remove assets\/current\/obsolete\.png/);
  assert.match(dryRun.stdout, /would remove assets\/stale\//);
  assert.match(dryRun.stdout, /00 RAW LIST\.md: publication control file/);
  assert.match(dryRun.stdout, /AGENTS\.override\.md: agent instruction file/);
  assert.equal((await stat(path.join(root, 'out', 'stale.md'))).isFile(), true);
  assert.equal((await stat(path.join(root, 'assets', 'stale'))).isDirectory(), true);

  const firstRun = await runSync(root);
  assert.match(firstRun.stdout, /removed out\/stale\.md/);
  assert.match(firstRun.stdout, /removed assets\/current\/obsolete\.png/);
  assert.match(firstRun.stdout, /removed assets\/stale\//);
  await assert.rejects(stat(path.join(root, 'out', 'stale.md')), { code: 'ENOENT' });
  await assert.rejects(stat(path.join(root, 'assets', 'stale')), { code: 'ENOENT' });
  await assert.rejects(stat(path.join(root, 'assets', 'current', 'obsolete.png')), { code: 'ENOENT' });
  assert.equal(await readFile(path.join(root, 'out', 'hand-written.md'), 'utf8'), '# Hand-written\n');

  const manifestPath = path.join(root, 'assets', '.obsidian-notes-sync-manifest.json');
  const firstManifest = await readFile(manifestPath, 'utf8');
  const manifest = JSON.parse(firstManifest);
  assert.deepEqual(manifest.notes, ['out/current.md']);
  assert.deepEqual(manifest.assets, []);
  await assert.rejects(stat(path.join(root, 'out', '00-raw-list.md')), { code: 'ENOENT' });
  await assert.rejects(stat(path.join(root, 'out', 'agents-override.md')), { code: 'ENOENT' });

  const secondRun = await runSync(root);
  assert.doesNotMatch(secondRun.stdout, /(?:^|\n)(?:would )?removed? /);
  assert.match(secondRun.stdout, /unchanged out\/current\.md/);
  assert.match(secondRun.stdout, /unchanged assets\/\.obsidian-notes-sync-manifest\.json/);
  assert.equal(await readFile(manifestPath, 'utf8'), firstManifest);
});
